//
// Created by rolf on 6-8-23.
//

#ifndef MIPWORKSHOP2024_SRC_PRESOLVE_TUCOLUMNSUBMATRIX_H
#define MIPWORKSHOP2024_SRC_PRESOLVE_TUCOLUMNSUBMATRIX_H

class TUColumnSubmatrix {

};

#endif //MIPWORKSHOP2024_SRC_PRESOLVE_TUCOLUMNSUBMATRIX_H
